// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  var coffee, config, hapi, modules, port, routes, server;

  console.log("$PORT is `" + process.env.PORT + "`");

  coffee = require('coffee-script');

  modules = ['templates', 'database', 'github', 'jobs', 'email', 'tokens', 'errors'];

  modules.forEach(function(m) {
    return require("./" + m).initialise();
  });

  hapi = require('hapi');

  config = require('../config');

  routes = require('./routes');

  port = parseInt(process.env.PORT || '8080');

  server = hapi.createServer(process.env.HOST || 'localhost', port, {
    views: {
      path: 'views',
      engines: {
        html: 'handlebars'
      }
    },
    auth: {
      scheme: 'cookie',
      password: config.cookies.password,
      isSecure: false,
      redirectTo: '/signin',
      appendNext: false
    },
    cache: config.sessions
  });

  routes.initialise(server);

  console.log("server: awaiting connections on port " + port);

  server.start();

}).call(this);
