// Generated by CoffeeScript 2.0.0-beta5
void function () {
  var coffee, config, hapi, modules, port, routes, server;
  'use strict';
  coffee = require('coffee-script-redux');
  coffee.register();
  modules = [
    'templates',
    'database',
    'github',
    'jobs',
    'email'
  ];
  modules.forEach(function (m) {
    return require('./' + m).initialise();
  });
  hapi = require('hapi');
  config = require('../config');
  routes = require('./routes');
  port = 8080;
  server = hapi.createServer('localhost', port, {
    views: {
      path: 'views',
      engines: { html: 'handlebars' }
    },
    auth: {
      scheme: 'cookie',
      password: config.cookies.password,
      isSecure: false,
      redirectTo: '/signin',
      appendNext: false
    },
    cache: config.sessions.development
  });
  routes.initialise(server);
  console.log('server: awaiting connections on port ' + port);
  server.start();
}.call(this);
