// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  var attributes, selectors, showOrHideControl;

  attributes = {
    control: 'data-visibility-control',
    option: 'data-visibility-option'
  };

  selectors = {
    control: "[" + attributes.control + "]",
    option: "[" + attributes.option + "]"
  };

  showOrHideControl = function($controller, $controllee, value) {
    if ($controller.val() === value) {
      return $controllee.show();
    } else {
      return $controllee.hide();
    }
  };

  $(function() {
    return $(selectors.control).each(function() {
      var $controllee, $controller, value;
      $controller = $(this);
      $controllee = $($controller.attr(attributes.control));
      value = $controller.attr(attributes.option);
      showOrHideControl($controller, $controllee, value);
      return $controller.on('change', function() {
        return showOrHideControl($controller, $controllee, value);
      });
    });
  });

}).call(this);
